#!/usr/bin/env python3
"""
Build the position index used by the reading/memorisation tracker.

Usage:
    python3 build_index.py

Reads the per-surah data files already produced by build_surah.py and derives
three lookup tables, written to Quran/assets/data/index.js as
window.QURAN_INDEX.

Why an index at all
-------------------
Every tracked thing — a reading session, a hifz page, a review interval, a
plan's daily portion — is a *range of ayahs*. Ranges are painful as
(surah, ayah) pairs: "how much is left" needs a loop over surahs, and "the next
twenty ayahs" can cross a surah boundary. Numbering all 6236 ayahs 1..6236 turns
every one of those questions into integer arithmetic.

The tables
----------
surahStart[s]  global index of the first ayah of surah s      (1..114, plus a
               sentinel at 115 so surah length is a subtraction)
pageStart[p]   global index of the first ayah *starting* on mushaf page p
               (1..604, sentinel at 605)
juzStart[j]    global index of the first ayah of juz j         (1..30,
               sentinel at 31)

A page that no ayah starts on — one long ayah spanning the whole sheet — would
leave a hole. Those are back-filled with the previous page's value so the array
stays non-decreasing and a binary search still lands correctly.
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.normpath(os.path.join(HERE, '..', 'assets', 'data'))

TOTAL_AYAHS = 6236
TOTAL_PAGES = 604
TOTAL_JUZ = 30


def load_global(path, name):
    """Read a file written as `window.NAME = {...};` and return the object."""
    raw = open(path, encoding='utf-8').read()
    m = re.search(r'window\.' + name + r'\s*=\s*', raw)
    if not m:
        raise SystemExit('%s: no assignment to window.%s' % (path, name))
    body = raw[m.end():].rstrip()
    if body.endswith(';'):
        body = body[:-1]
    return json.loads(body)


def build():
    surah_start = [0] * 116          # 1..114 used, 115 is the sentinel
    page_start = [0] * (TOTAL_PAGES + 2)
    juz_start = [0] * (TOTAL_JUZ + 2)

    g = 0                            # running global ayah index
    for s in range(1, 115):
        path = os.path.join(DATA, '%03d.js' % s)
        if not os.path.exists(path):
            raise SystemExit('missing %s — run build_surah.py all first' % path)
        surah = load_global(path, 'QURAN_SURAH')
        verses = surah['verses']

        surah_start[s] = g + 1
        for v in verses:
            g += 1
            p = v.get('page')
            j = v.get('juz')
            if p and not page_start[p]:
                page_start[p] = g
            if j and not juz_start[j]:
                juz_start[j] = g

        if len(verses) != surah['versesCount']:
            raise SystemExit('surah %d: %d verses but versesCount says %d'
                             % (s, len(verses), surah['versesCount']))

    if g != TOTAL_AYAHS:
        raise SystemExit('counted %d ayahs, expected %d' % (g, TOTAL_AYAHS))

    surah_start[115] = g + 1
    page_start[TOTAL_PAGES + 1] = g + 1
    juz_start[TOTAL_JUZ + 1] = g + 1

    # Back-fill any page or juz no ayah began on, so the arrays never decrease.
    holes = []
    for p in range(1, TOTAL_PAGES + 2):
        if not page_start[p]:
            holes.append(p)
            page_start[p] = page_start[p - 1] if p > 1 else 1
    for j in range(1, TOTAL_JUZ + 2):
        if not juz_start[j]:
            juz_start[j] = juz_start[j - 1] if j > 1 else 1

    for arr, label in ((surah_start[1:116], 'surahStart'),
                       (page_start[1:TOTAL_PAGES + 2], 'pageStart'),
                       (juz_start[1:TOTAL_JUZ + 2], 'juzStart')):
        for i in range(1, len(arr)):
            if arr[i] < arr[i - 1]:
                raise SystemExit('%s is not non-decreasing at %d' % (label, i))

    if holes:
        print('pages with no ayah starting on them (back-filled): %s' % holes)

    out = {
        'totalAyahs': TOTAL_AYAHS,
        'totalPages': TOTAL_PAGES,
        'totalJuz': TOTAL_JUZ,
        # index 0 is padding so the arrays can be read 1-based, matching how
        # surahs, pages and juz are numbered everywhere else.
        'surahStart': surah_start[:116],
        'pageStart': page_start[:TOTAL_PAGES + 2],
        'juzStart': juz_start[:TOTAL_JUZ + 2],
    }

    path = os.path.join(DATA, 'index.js')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('/* generated by tools/build_index.py — do not edit by hand */\n')
        f.write('window.QURAN_INDEX = ')
        json.dump(out, f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')

    print('wrote %s (%.1f KB)' % (path, os.path.getsize(path) / 1024.0))
    print('  %d ayahs, %d pages, %d juz' % (g, TOTAL_PAGES, TOTAL_JUZ))


if __name__ == '__main__':
    sys.exit(build())
