#!/usr/bin/env python3
"""
Build static per-surah data files for the Qur'an reader.

Usage:
    python3 build_surah.py 31            # one surah
    python3 build_surah.py 1 2 3         # several
    python3 build_surah.py all           # all 114
    python3 build_surah.py meta          # regenerate surahs.js only

Sources (fetched once, then baked into static files so the site works offline):
  * quran.com API v4 — Uthmani text, Saheeh International translation,
    per-word transliteration + gloss, tafsirs
Outputs, relative to Quran/assets/data/:
  surahs.js        metadata for all 114     -> window.QURAN_SURAHS
  NNN.js           verses + words for NNN   -> window.QURAN_SURAH
  tafsir/NNN.js    tafsir for NNN (lazy)    -> window.QURAN_TAFSIR

These are .js files assigning a global rather than .json fetched with fetch(),
so the reader also works when the pages are opened straight from disk —
browsers block fetch() over file:// but load <script> tags normally.
"""

import concurrent.futures as futures
import json
import os
import re
import sys
import threading
import time
import urllib.error
import urllib.request

API = 'https://api.quran.com/api/v4'
HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.normpath(os.path.join(HERE, '..', 'assets', 'data'))
TAFSIR_DIR = os.path.join(DATA, 'tafsir')

TRANSLATION_ID = 20          # Saheeh International
TAFSIRS = [
    ('muyassar', 16,  'التفسير الميسر',        'ar'),
    ('saadi',    91,  'تفسير السعدي',          'ar'),
    ('kathir',   169, 'Ibn Kathir (Abridged)', 'en'),
]

UA = 'Mozilla/5.0 (compatible; static-quran-builder/1.0)'


def dump(path, obj, global_name):
    """Write data as a script that assigns to a window global."""
    with open(path, 'w', encoding='utf-8') as f:
        f.write('/* generated by tools/build_surah.py — do not edit by hand */\n')
        f.write('window.' + global_name + ' = ')
        json.dump(obj, f, ensure_ascii=False, separators=(',', ':'))
        f.write(';\n')


def load_dump(path):
    """Read back a file written by dump()."""
    raw = open(path, encoding='utf-8').read()
    body = raw[raw.index('=') + 1:].strip()
    if body.endswith(';'):
        body = body[:-1]
    return json.loads(body)


def get(url, tries=4):
    for attempt in range(tries):
        try:
            req = urllib.request.Request(url, headers={'User-Agent': UA, 'Accept': 'application/json'})
            with urllib.request.urlopen(req, timeout=60) as r:
                return json.loads(r.read().decode('utf-8'))
        except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, OSError) as e:
            if attempt == tries - 1:
                raise
            time.sleep(1.5 * (attempt + 1))


TAG = re.compile(r'<[^>]+>')
WS = re.compile(r'[ \t ]+')


def clean(html):
    """Turn tafsir HTML into plain text, keeping paragraph breaks."""
    if not html:
        return ''
    s = html.replace('\r', '')
    s = re.sub(r'(?i)<br\s*/?>', '\n', s)
    s = re.sub(r'(?i)</p\s*>', '\n\n', s)
    s = re.sub(r'(?i)</div\s*>', '\n', s)
    s = re.sub(r'(?i)</h[1-6]\s*>', '\n\n', s)
    s = TAG.sub('', s)
    s = (s.replace('&nbsp;', ' ').replace('&amp;', '&')
           .replace('&lt;', '<').replace('&gt;', '>')
           .replace('&quot;', '"').replace('&#39;', "'"))
    s = WS.sub(' ', s)
    s = re.sub(r'\n\s*\n\s*\n+', '\n\n', s)
    return s.strip()


FOOTNOTE = re.compile(r'<sup[^>]*foot_note[^>]*>.*?</sup>', re.S | re.I)


def clean_translation(html):
    """Saheeh International text carries footnote superscripts — drop them."""
    return clean(FOOTNOTE.sub('', html or ''))


def fetch_meta():
    ch = get(API + '/chapters?language=en')['chapters']
    out = []
    for c in ch:
        out.append({
            'id': c['id'],
            'nameAr': c['name_arabic'],
            'nameEn': c['name_simple'],
            'nameTr': c['name_complex'],
            'meaning': c['translated_name']['name'],
            'place': c['revelation_place'],
            'order': c['revelation_order'],
            'verses': c['verses_count'],
            'pages': c['pages'],
            'bismillah': c['bismillah_pre'],
        })
    return out


def fetch_verses(sid, total):
    """All verses of a surah, with words, translation and Uthmani text."""
    verses, page, per = [], 1, 50
    while True:
        url = (f'{API}/verses/by_chapter/{sid}'
               f'?words=true&word_fields=text_uthmani,transliteration,location,'
               f'code_v2,line_number,page_number'
               f'&fields=text_uthmani&translations={TRANSLATION_ID}'
               f'&per_page={per}&page={page}')
        d = get(url)
        verses.extend(d['verses'])
        pg = d.get('pagination') or {}
        if not pg.get('next_page'):
            break
        page = pg['next_page']
        time.sleep(0.15)
    if len(verses) != total:
        raise SystemExit(f'surah {sid}: expected {total} verses, got {len(verses)}')
    return verses


def fetch_tafsir(sid, tid):
    """Tafsir for a whole surah, keyed by verse number."""
    out, page = {}, 1
    while True:
        d = get(f'{API}/tafsirs/{tid}/by_chapter/{sid}?per_page=50&page={page}')
        for t in d.get('tafsirs', []):
            key = t.get('verse_key') or ''
            if ':' in key:
                out[int(key.split(':')[1])] = clean(t.get('text'))
        pg = d.get('pagination') or {}
        if not pg.get('next_page'):
            break
        page = pg['next_page']
        time.sleep(0.15)
    return out


PRINT_LOCK = threading.Lock()


def build(sid, meta_by_id, skip_existing=False):
    m = meta_by_id[sid]
    out_v = os.path.join(DATA, f'{sid:03d}.js')
    out_t = os.path.join(TAFSIR_DIR, f'{sid:03d}.js')
    if skip_existing and os.path.exists(out_v) and os.path.exists(out_t) \
            and os.path.getsize(out_v) > 200 and os.path.getsize(out_t) > 200:
        with PRINT_LOCK:
            print(f'  surah {sid:>3} {m["nameEn"]:<16} — already built, skipped')
        return True

    raw = fetch_verses(sid, m['verses'])
    verses = []
    for v in raw:
        n = int(v['verse_key'].split(':')[1])
        words = []
        glyphs = []               # every glyph on the page, medallions included
        for w in v.get('words', []):
            if w.get('code_v2') and w.get('line_number'):
                glyphs.append({
                    'g': w['code_v2'],
                    'l': w['line_number'],
                    'p': w.get('page_number') or 0,
                    'e': 1 if w.get('char_type_name') == 'end' else 0,
                })
            if w.get('char_type_name') != 'word':
                continue          # the medallion is not a word for word-by-word
            words.append({
                'a': w.get('text_uthmani') or '',
                't': ((w.get('transliteration') or {}).get('text') or ''),
                'm': ((w.get('translation') or {}).get('text') or ''),
            })
        tr = ' '.join(w['t'] for w in words if w['t']).strip()
        en = ''
        if v.get('translations'):
            en = clean_translation(v['translations'][0].get('text'))
        verses.append({
            'n': n,
            'ar': v.get('text_uthmani') or '',
            'tr': tr,
            'en': en,
            'page': v.get('page_number'),
            'juz': v.get('juz_number'),
            'sajda': bool(v.get('sajdah_number')),
            'w': words,
            'gl': glyphs,
        })

    # Rebuild the muṣḥaf page layout: page -> line -> the words on that line,
    # so the reader can lay out real 15-line pages instead of reflowing text.
    layout = {}
    for v in verses:
        for w in v['gl']:
            pg = w['p'] or v['page']
            line = layout.setdefault(str(pg), {}).setdefault(str(w['l']), [])
            entry = {'g': w['g'], 'v': v['n']}
            if w['e']:
                entry['e'] = 1
            line.append(entry)

    # the glyph list was only scaffolding for the layout
    for v in verses:
        del v['gl']

    # The chapters endpoint reports only the opening page for several short
    # sūrahs ('Abasa, al-Inshiqāq, al-Ghāshiya, al-Balad, ash-Sharḥ, al-'Alaq),
    # even though their closing verses run onto the next sheet. The per-word
    # page numbers are authoritative, so derive the range from those.
    seen_pages = sorted({v['page'] for v in verses if v.get('page')})
    page_range = [seen_pages[0], seen_pages[-1]] if seen_pages else m['pages']

    surah = {
        'id': sid,
        'layout': layout, 'nameAr': m['nameAr'], 'nameEn': m['nameEn'], 'nameTr': m['nameTr'],
        'meaning': m['meaning'], 'place': m['place'], 'order': m['order'],
        'versesCount': m['verses'], 'pages': page_range, 'bismillah': m['bismillah'],
        'translation': 'Saheeh International',
        'verses': verses,
    }
    os.makedirs(DATA, exist_ok=True)
    fn = os.path.join(DATA, f'{sid:03d}.js')
    dump(fn, surah, 'QURAN_SURAH')

    taf = {'sources': [{'key': k, 'name': name, 'lang': lang} for k, _, name, lang in TAFSIRS],
           'verses': {}}
    # the three tafsirs are independent requests — fetch them together
    with futures.ThreadPoolExecutor(max_workers=3) as ex:
        jobs = {ex.submit(fetch_tafsir, sid, tid): key for key, tid, _, _ in TAFSIRS}
        for job in futures.as_completed(jobs):
            key = jobs[job]
            for n, text in job.result().items():
                taf['verses'].setdefault(str(n), {})[key] = text
    os.makedirs(TAFSIR_DIR, exist_ok=True)
    tf = os.path.join(TAFSIR_DIR, f'{sid:03d}.js')
    dump(tf, taf, 'QURAN_TAFSIR')

    with PRINT_LOCK:
        print(f'  surah {sid:>3} {m["nameEn"]:<16} ({m["verses"]:>3} v) '
              f'verses {os.path.getsize(fn)//1024:>4}KB · tafsir {os.path.getsize(tf)//1024:>4}KB')
    return True


def main(argv):
    if not argv:
        print(__doc__)
        return 1

    os.makedirs(DATA, exist_ok=True)
    meta_path = os.path.join(DATA, 'surahs.js')
    if argv[0] == 'meta' or not os.path.exists(meta_path):
        print('fetching chapter metadata …')
        meta = fetch_meta()
        dump(meta_path, meta, 'QURAN_SURAHS')
        print(f'  wrote surahs.js ({len(meta)} surahs)')
        if argv[0] == 'meta':
            return 0
    else:
        meta = load_dump(meta_path)

    meta_by_id = {m['id']: m for m in meta}
    ids = list(range(1, 115)) if argv[0] == 'all' else [int(a) for a in argv if a.isdigit()]

    resume = '--resume' in argv or 'all' in argv
    workers = 5
    print(f'building {len(ids)} surah(s) with {workers} workers'
          + (' (skipping ones already built)' if resume else '') + ':')

    failed = []
    with futures.ThreadPoolExecutor(max_workers=workers) as ex:
        jobs = {ex.submit(build, sid, meta_by_id, resume): sid for sid in ids}
        for job in futures.as_completed(jobs):
            sid = jobs[job]
            try:
                job.result()
            except Exception as e:
                failed.append((sid, str(e)[:90]))
                with PRINT_LOCK:
                    print(f'  surah {sid:>3} FAILED: {str(e)[:90]}')

    if failed:
        print(f'\n{len(failed)} surah(s) failed: ' + ', '.join(str(f[0]) for f in failed))
        print('re-run the same command to retry only those.')
        return 1
    print('\ndone.')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
